return function()
	local wk = require("which-key")

	wk.setup({
		preset = "modern",
		delay = 300,
		expand = 1,
		notify = false,
		triggers = { "<leader>" },
		plugins = {
			presets = {
				operators = false,
				motions = false,
				text_objects = false,
				g = false,
			},
		},
		win = {
			border = "rounded",
			padding = { 1, 2 },
			title = true,
			title_pos = "center",
			zindex = 1000,
		},
		layout = { width = { min = 20, max = 50 }, spacing = 3, align = "left" },
		icons = { breadcrumb = ">", separator = "->", group = "+" },
	})

	wk.register({
		["<leader>a"] = {
			name = "+autosave",
			a = { "<cmd>AutoSaveToggle<CR>", "Toggle AutoSave" },
		},
		["<leader>f"] = {
			name = "+find",
			f = { "<cmd>Telescope find_files hidden=true follow=true<CR>", "Find File" },
			g = { "<cmd>Telescope live_grep hidden=true<CR>", "Live Grep" },
			b = { "<cmd>Telescope buffers<CR>", "Buffers" },
			h = { "<cmd>Telescope help_tags<CR>", "Help Tags" },
			r = { "<cmd>Telescope oldfiles<CR>", "Recent Files" },
			k = { "<cmd>Telescope keymaps<CR>", "Keymaps" },
			s = { "<cmd>Telescope lsp_document_symbols<CR>", "Document Symbols" },
			S = { "<cmd>Telescope lsp_workspace_symbols<CR>", "Workspace Symbols" },
			d = { "<cmd>Telescope lsp_definitions<CR>", "Definitions" },
			i = { "<cmd>Telescope lsp_implementations<CR>", "Implementations" },
		},
		["<leader>b"] = {
			name = "+buffer",
			b = { "<cmd>BufferClose<CR>", "Close" },
			n = { "<cmd>BufferNext<CR>", "Next" },
			p = { "<cmd>BufferPrevious<CR>", "Previous" },
		},
		["<leader>g"] = {
			name = "+git",
			c = { "<cmd>Telescope git_commits<CR>", "Commits" },
			b = { "<cmd>Telescope git_branches<CR>", "Branches" },
			B = { "<cmd>DiffviewFileHistory %<CR>", "File History" },
			s = { "<cmd>DiffviewOpen -- %<CR>", "Diff Current File" },
			S = { "<cmd>DiffviewOpen<CR>", "Diff Workspace" },
			D = { "<cmd>DiffviewClose<CR>", "Close Diff View" },
			j = { "<cmd>lua require('gitsigns').nav_hunk('next')<CR>", "Next Hunk" },
			k = { "<cmd>lua require('gitsigns').nav_hunk('prev')<CR>", "Prev Hunk" },
			p = { "<cmd>lua require('gitsigns').preview_hunk()<CR>", "Preview Hunk" },
			l = { "<cmd>lua require('gitsigns').toggle_current_line_blame()<CR>", "Toggle Blame" },
			h = {
				name = "+hunk",
				s = { "<cmd>lua require('gitsigns').stage_hunk()<CR>", "Stage Hunk" },
				S = { "<cmd>lua require('gitsigns').stage_buffer()<CR>", "Stage Buffer" },
				u = { "<cmd>lua require('gitsigns').stage_hunk()<CR>", "Undo Stage Hunk" },
				r = { "<cmd>lua require('gitsigns').reset_hunk()<CR>", "Reset Hunk" },
				R = { "<cmd>lua require('gitsigns').reset_buffer()<CR>", "Reset Buffer" },
			},
		},
		["<leader>l"] = {
			name = "+lsp",
			a = { "<cmd>lua vim.lsp.buf.code_action()<CR>", "Code Action" },
			d = { "<cmd>lua vim.diagnostic.open_float()<CR>", "Diagnostics" },
			D = { "<cmd>lua vim.lsp.buf.declaration()<CR>", "Declaration" },
			g = { "<cmd>lua vim.lsp.buf.definition()<CR>", "Definition" },
			i = { "<cmd>lua vim.lsp.buf.implementation()<CR>", "Implementation" },
			r = { "<cmd>lua vim.lsp.buf.references()<CR>", "References" },
			n = { "<cmd>lua vim.lsp.buf.rename()<CR>", "Rename" },
			f = { "<cmd>lua require('config.actions').format_document()<CR>", "Format" },
			h = { "<cmd>lua vim.lsp.buf.hover()<CR>", "Hover" },
			j = { "<cmd>lua require('config.actions').diagnostic_next()<CR>", "Next Diagnostic" },
			k = { "<cmd>lua require('config.actions').diagnostic_prev()<CR>", "Previous Diagnostic" },
			t = { "<cmd>lua vim.lsp.buf.type_definition()<CR>", "Type Definition" },
			s = { "<cmd>lua vim.lsp.buf.document_symbol()<CR>", "Document Symbols" },
			S = { "<cmd>lua vim.lsp.buf.workspace_symbol()<CR>", "Workspace Symbols" },
		},
		["<leader>x"] = {
			name = "+diagnostics",
			x = { "<cmd>Trouble diagnostics toggle<CR>", "Toggle" },
			w = { "<cmd>Trouble diagnostics toggle<CR>", "Workspace" },
			d = { "<cmd>Trouble diagnostics toggle filter.buf=0<CR>", "Document" },
			q = { "<cmd>Trouble qflist toggle<CR>", "Quickfix" },
		},
		["<leader>t"] = {
			name = "+terminal",
			["`"] = { "<cmd>ToggleTerm<CR>", "Toggle" },
			f = { "<cmd>ToggleTerm direction=float<CR>", "Float" },
			v = { "<cmd>ToggleTerm direction=vertical<CR>", "Vertical" },
			h = { "<cmd>ToggleTerm direction=horizontal<CR>", "Horizontal" },
			g = { "<cmd>lua require('toggleterm').exec('lazygit', nil, nil, nil, 'float')<CR>", "Lazygit" },
		},
		["<leader>s"] = {
			name = "+session",
			s = { "<cmd>Autosession save<CR>", "Save" },
			r = { "<cmd>Autosession restore<CR>", "Restore" },
			d = { "<cmd>Autosession delete<CR>", "Delete" },
		},
		["<leader>r"] = {
			name = "+search/replace",
			w = { "<cmd>lua require('spectre').open_visual({select_word=true})<CR>", "Replace word" },
			p = { "<cmd>lua require('spectre').open()<CR>", "Replace in project" },
			f = { "<cmd>lua require('spectre').open_file_search()<CR>", "Replace in file" },
		},
		["<leader>re"] = {
			name = "+extract",
			e = { ":Refactor extract ", "Extract to function" },
			f = { ":Refactor extract_to_file ", "Extract to file" },
			i = { ":Refactor inline_var", "Inline variable" },
			b = { ":Refactor extract_block ", "Extract block" },
		},
		["<leader>th"] = {
			name = "+theme",
			n = { "<cmd>lua require('plugins.themes').next()<CR>", "Next Theme" },
			p = { "<cmd>lua require('plugins.themes').previous()<CR>", "Previous Theme" },
		},
		["<leader>w"] = {
			name = "+write/quit",
			s = { "<cmd>w<CR>", "Save" },
			q = { "<cmd>wq<CR>", "Save & Quit" },
			a = { "<cmd>BufOnly<CR>", "Close Other Buffers" },
		},
		["<leader>d"] = {
			name = "+debug",
			c = { "<cmd>lua require('dap').continue()<CR>", "Continue" },
			i = { "<cmd>lua require('dap').step_into()<CR>", "Step into" },
			o = { "<cmd>lua require('dap').step_over()<CR>", "Step over" },
			O = { "<cmd>lua require('dap').step_out()<CR>", "Step out" },
			r = { "<cmd>lua require('dap').repl.toggle()<CR>", "Toggle REPL" },
			l = { "<cmd>lua require('dap').run_last()<CR>", "Run last" },
			u = { "<cmd>lua require('dapui').toggle()<CR>", "Toggle DAP UI" },
			x = { "<cmd>lua require('dap').terminate()<CR>", "Terminate" },
		},
		["<leader>j"] = {
			name = "+java",
			r = { "<cmd>lua require('config.actions').run_java_file()<CR>", "Run Java File" },
			R = { "<cmd>lua require('config.actions').run_spring_boot()<CR>", "Run Spring Boot" },
			b = { "<cmd>lua require('config.actions').run_java_build()<CR>", "Build Project" },
			x = { "<cmd>lua require('config.actions').run_java_tests()<CR>", "Run Project Tests" },
		},
		["<leader>n"] = {
			name = "+nvimtree",
			n = { "<cmd>NvimTreeToggle<CR>", "Toggle NvimTree" },
			x = {
				"<cmd>lua local ok,api=pcall(require,'nvim-tree.api'); if ok and api.tree and api.tree.expand_all then api.tree.expand_all() end<CR>",
				"Expand All Folders",
			},
			c = {
				"<cmd>lua local ok,api=pcall(require,'nvim-tree.api'); if ok and api.tree and api.tree.collapse_all then api.tree.collapse_all() end<CR>",
				"Collapse All Folders",
			},
		},
		["<leader>e"] = { "<cmd>NvimTreeFocus<CR>", "Focus NvimTree" },
		["<leader>m"] = { "<cmd>AerialToggle!<CR>", "Toggle Structure" },
		["<leader>dd"] = { "<cmd>Telescope diagnostics<CR>", "Workspace Diagnostics" },
	})
end
